name: lab_4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_calendar_carousel: ^2.4.4
  geolocator: ^13.0.2
  http: 1.2.2
  flutter_polyline_points: ^2.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
