// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF7RYPzKGk9DMmnR9bUubIshxFsbGW1kk',
    appId: '1:1089926019578:web:869ba8bcc6703b5a708c43',
    messagingSenderId: '1089926019578',
    projectId: 'lab-4-f5081',
    authDomain: 'lab-4-f5081.firebaseapp.com',
    storageBucket: 'lab-4-f5081.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe8QkkMfZt0M7Tpy1aiKRfSCRvoMdZL2g',
    appId: '1:1089926019578:android:8d12f33c7d870a02708c43',
    messagingSenderId: '1089926019578',
    projectId: 'lab-4-f5081',
    storageBucket: 'lab-4-f5081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD65aeHtmZmjOra64_7-pRlSYriuZdcc7U',
    appId: '1:1089926019578:ios:699e02ec9dd40361708c43',
    messagingSenderId: '1089926019578',
    projectId: 'lab-4-f5081',
    storageBucket: 'lab-4-f5081.firebasestorage.app',
    iosBundleId: 'com.example.lab4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD65aeHtmZmjOra64_7-pRlSYriuZdcc7U',
    appId: '1:1089926019578:ios:699e02ec9dd40361708c43',
    messagingSenderId: '1089926019578',
    projectId: 'lab-4-f5081',
    storageBucket: 'lab-4-f5081.firebasestorage.app',
    iosBundleId: 'com.example.lab4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF7RYPzKGk9DMmnR9bUubIshxFsbGW1kk',
    appId: '1:1089926019578:web:17e0848a2e42f347708c43',
    messagingSenderId: '1089926019578',
    projectId: 'lab-4-f5081',
    authDomain: 'lab-4-f5081.firebaseapp.com',
    storageBucket: 'lab-4-f5081.firebasestorage.app',
  );
}
